In [1]:
import pandas as pd
import altair as alt
import utils

In [120]:
from imp import reload
reload(utils)

# Load data

In [2]:
bay_area_counties = [
    'Alameda', 'Contra Costa', 'Marin', 'San Francisco', 'San Mateo', 'Santa Clara', 'Napa', 'Sonoma', 'Solano'
]

In [3]:
pop_estimate_components_df = utils.load_population_projections_df()

In [4]:
historical_components_df = utils.load_historical_estimates_df()

In [5]:
bay_area_historical_components_df = historical_components_df.loc[lambda x: x['County'].isin(bay_area_counties)]

In [6]:
bay_area_projections_df = pop_estimate_components_df.loc[lambda x: x['County'].isin(bay_area_counties)]

# Look at birth/death rates

In [7]:
bay_area_historical_components_df[['County', 'Year']].assign(
    birth_rate=bay_area_historical_components_df['Births'] / bay_area_historical_components_df['Population (July 1)']
).set_index(['County', 'Year']).unstack().applymap('{:.2%}'.format)

              birth_rate                                                   \
Year                2011   2012   2013   2014   2015   2016   2017   2018
County
Alameda            1.25%  1.22%  1.23%  1.22%  1.20%  1.20%  1.18%  1.10%
Contra Costa       1.16%  1.11%  1.12%  1.11%  1.12%  1.11%  1.07%  1.05%
Marin              0.93%  0.91%  0.90%  0.93%  0.88%  0.87%  0.85%  0.83%
Napa               1.09%  1.10%  1.01%  1.05%  1.04%  1.03%  0.92%  0.90%
San Francisco      1.08%  1.05%  1.08%  1.05%  1.05%  1.03%  1.02%  0.98%
San Mateo          1.25%  1.21%  1.21%  1.18%  1.20%  1.17%  1.13%  1.08%
Santa Clara        1.32%  1.27%  1.29%  1.24%  1.23%  1.20%  1.16%  1.11%
Solano             1.25%  1.21%  1.22%  1.23%  1.23%  1.19%  1.19%  1.16%
Sonoma             1.09%  1.03%  1.02%  1.00%  1.01%  1.02%  0.95%  0.90%


Year            2019 Apr-Jun 2010
County
Alameda        1.09%        0.32%
Contra Costa   1.04%        0.29%
Marin          0.81%        0.23%
Napa           0.84%        0.29%
San Francisco  0.97%        0.26%
San Mateo      1.06%        0.32%
Santa Clara    1.08%        0.33%
Solano         1.14%        0.29%
Sonoma         0.90%        0.29%

In [8]:
bay_area_historical_components_df[['County', 'Year']].assign(
    birth_rate=bay_area_historical_components_df['Deaths'] / bay_area_historical_components_df['Population (July 1)']
).set_index(['County', 'Year']).unstack().applymap('{:.2%}'.format)

              birth_rate                                                   \
Year                2011   2012   2013   2014   2015   2016   2017   2018
County
Alameda            0.59%  0.59%  0.61%  0.58%  0.59%  0.59%  0.61%  0.60%
Contra Costa       0.68%  0.65%  0.67%  0.65%  0.68%  0.69%  0.69%  0.70%
Marin              0.72%  0.73%  0.73%  0.72%  0.75%  0.72%  0.75%  0.76%
Napa               0.83%  0.81%  0.89%  0.83%  0.79%  0.86%  0.92%  0.91%
San Francisco      0.70%  0.66%  0.68%  0.64%  0.65%  0.65%  0.65%  0.67%
San Mateo          0.62%  0.62%  0.63%  0.59%  0.62%  0.60%  0.63%  0.62%
Santa Clara        0.50%  0.50%  0.51%  0.50%  0.52%  0.52%  0.53%  0.52%
Solano             0.68%  0.69%  0.69%  0.71%  0.73%  0.74%  0.77%  0.80%
Sonoma             0.79%  0.78%  0.79%  0.80%  0.80%  0.82%  0.85%  0.83%


Year            2019 Apr-Jun 2010
County
Alameda        0.59%        0.14%
Contra Costa   0.69%        0.16%
Marin          0.74%        0.19%
Napa           0.81%        0.22%
San Francisco  0.66%        0.16%
San Mateo      0.61%        0.16%
Santa Clara    0.52%        0.12%
Solano         0.82%        0.17%
Sonoma         0.81%        0.21%

In [9]:
pop_estimate_components_df

,County,Start Year,Start Population,Births,Deaths,Net migrants,End Year,End Population
1,Alameda,2010,1516357,19217,9073,8035,2011,1534536
2,Alameda,2011,1534536,18972,9252,12829,2012,1557085
3,Alameda,2012,1557085,19464,9668,11053,2013,1577934
4,Alameda,2013,1577934,19486,9302,12899,2014,1601017
5,Alameda,2014,1601017,19495,9647,10655,2015,1621520
...,...,...,...,...,...,...,...,...
2953,Yuba,2055,115759,1748,886,413,2056,117034
2954,Yuba,2056,117034,1730,911,410,2057,118263
2955,Yuba,2057,118263,1757,886,409,2058,119543
2956,Yuba,2058,119543,1762,928,419,2059,120796
2957,Yuba,2059,120796,1758,947,421,2060,122028

In [10]:
births_df = bay_area_projections_df[[
    'County', 'Start Year'
]].assign(
    birth_rate=bay_area_projections_df['Births'] / bay_area_projections_df['Start Population']
)

births_df.set_index(['County', 'Start Year']).unstack().applymap('{:.2%}'.format)

              birth_rate                                                   \
Start Year          2010   2011   2012   2013   2014   2015   2016   2017
County
Alameda            1.27%  1.24%  1.25%  1.23%  1.22%  1.21%  1.19%  1.11%
Contra Costa       1.17%  1.12%  1.14%  1.12%  1.14%  1.13%  1.08%  1.06%
Marin              0.94%  0.91%  0.91%  0.94%  0.88%  0.88%  0.85%  0.84%
Napa               1.10%  1.11%  1.01%  1.06%  1.04%  1.03%  0.92%  0.90%
San Francisco      1.10%  1.07%  1.09%  1.06%  1.07%  1.04%  1.03%  0.98%
San Mateo          1.27%  1.23%  1.22%  1.19%  1.21%  1.18%  1.14%  1.09%
Santa Clara        1.34%  1.29%  1.31%  1.25%  1.25%  1.21%  1.17%  1.12%
Solano             1.25%  1.22%  1.23%  1.25%  1.24%  1.21%  1.20%  1.17%
Sonoma             1.10%  1.03%  1.03%  1.01%  1.02%  1.03%  0.95%  0.90%

                             ...                                            \
Start Year      2018   2019  ...   2050   2051   2052   2053   2054   2055
County                       ...
Alameda        1.10%  1.10%  ...  0.88%  0.87%  0.86%  0.86%  0.85%  0.84%
Contra Costa   1.05%  1.08%  ...  1.00%  1.02%  1.02%  1.04%  1.06%  1.07%
Marin          0.81%  0.69%  ...  0.76%  0.72%  0.72%  0.71%  0.71%  0.70%
Napa           0.84%  0.95%  ...  0.75%  0.74%  0.76%  0.77%  0.78%  0.78%
San Francisco  0.98%  0.97%  ...  0.87%  0.86%  0.86%  0.87%  0.88%  0.87%
San Mateo      1.07%  1.01%  ...  0.79%  0.78%  0.79%  0.78%  0.78%  0.77%
Santa Clara    1.08%  1.04%  ...  0.87%  0.86%  0.84%  0.82%  0.81%  0.79%
Solano         1.15%  1.20%  ...  1.01%  1.02%  1.02%  1.02%  1.02%  1.03%
Sonoma         0.90%  0.83%  ...  0.62%  0.61%  0.61%  0.60%  0.60%  0.60%


Start Year      2056   2057   2058   2059
County
Alameda        0.84%  0.84%  0.85%  0.84%
Contra Costa   1.07%  1.08%  1.08%  1.10%
Marin          0.70%  0.70%  0.70%  0.71%
Napa           0.80%  0.81%  0.82%  0.83%
San Francisco  0.86%  0.84%  0.84%  0.83%
San Mateo      0.78%  0.78%  0.77%  0.78%
Santa Clara    0.79%  0.79%  0.79%  0.79%
Solano         1.03%  1.04%  1.04%  1.04%
Sonoma         0.60%  0.60%  0.60%  0.61%

[9 rows x 50 columns]

In [11]:
%config InlineBackend.figure_format = 'retina'
alt.Chart(births_df, width=800, height=400, title='Birth rate predictions').mark_line().encode(
    x=alt.X('Start Year', title='Year', axis=alt.Axis(format='')),
    y=alt.Y('birth_rate', title='Birth rate', scale=alt.Scale(zero=False), axis=alt.Axis(format='%')),
    color='County'
)

alt.Chart(...)

In [12]:
bay_area_projections_df[[
    'County', 'Start Year'
]].assign(
    birth_rate=bay_area_projections_df['Deaths'] / bay_area_projections_df['Start Population']
).set_index(['County', 'Start Year']).unstack().applymap('{:.2%}'.format)

              birth_rate                                                   \
Start Year          2010   2011   2012   2013   2014   2015   2016   2017
County
Alameda            0.60%  0.60%  0.62%  0.59%  0.60%  0.59%  0.61%  0.60%
Contra Costa       0.69%  0.65%  0.67%  0.66%  0.69%  0.70%  0.70%  0.71%
Marin              0.72%  0.73%  0.73%  0.72%  0.75%  0.73%  0.74%  0.76%
Napa               0.84%  0.81%  0.89%  0.83%  0.80%  0.86%  0.92%  0.90%
San Francisco      0.71%  0.67%  0.69%  0.65%  0.66%  0.66%  0.66%  0.68%
San Mateo          0.63%  0.63%  0.63%  0.60%  0.63%  0.61%  0.63%  0.62%
Santa Clara        0.51%  0.51%  0.51%  0.51%  0.53%  0.53%  0.53%  0.53%
Solano             0.69%  0.69%  0.70%  0.71%  0.74%  0.75%  0.78%  0.80%
Sonoma             0.79%  0.78%  0.79%  0.80%  0.80%  0.82%  0.85%  0.83%

                             ...                                            \
Start Year      2018   2019  ...   2050   2051   2052   2053   2054   2055
County                       ...
Alameda        0.59%  0.61%  ...  0.98%  0.99%  0.99%  0.99%  0.99%  1.00%
Contra Costa   0.69%  0.69%  ...  1.15%  1.16%  1.14%  1.15%  1.13%  1.15%
Marin          0.74%  0.75%  ...  1.46%  1.49%  1.49%  1.48%  1.49%  1.45%
Napa           0.81%  0.90%  ...  1.19%  1.26%  1.21%  1.20%  1.24%  1.17%
San Francisco  0.66%  0.69%  ...  0.93%  0.94%  0.93%  0.93%  0.93%  0.93%
San Mateo      0.62%  0.65%  ...  1.19%  1.20%  1.21%  1.22%  1.22%  1.23%
Santa Clara    0.52%  0.54%  ...  0.92%  0.91%  0.93%  0.92%  0.92%  0.93%
Solano         0.82%  0.81%  ...  1.18%  1.17%  1.17%  1.16%  1.17%  1.15%
Sonoma         0.81%  0.83%  ...  1.53%  1.49%  1.47%  1.47%  1.50%  1.50%


Start Year      2056   2057   2058   2059
County
Alameda        0.99%  0.99%  0.99%  0.99%
Contra Costa   1.11%  1.12%  1.12%  1.10%
Marin          1.43%  1.41%  1.35%  1.39%
Napa           1.19%  1.16%  1.17%  1.18%
San Francisco  0.94%  0.94%  0.94%  0.95%
San Mateo      1.24%  1.24%  1.24%  1.25%
Santa Clara    0.95%  0.95%  0.95%  0.94%
Solano         1.15%  1.13%  1.12%  1.12%
Sonoma         1.49%  1.46%  1.48%  1.48%

[9 rows x 50 columns]

In [13]:
pop_estimate_components_df.query('County == "San Francisco"').applymap(lambda x: '{:,d}'.format(x) if isinstance(x, int) else x)

,County,Start Year,Start Population,Births,Deaths,Net migrants,End Year,End Population
1888,San Francisco,"2,010","810,369","8,897","5,727","7,696","2,011","821,235"
1889,San Francisco,"2,011","821,235","8,778","5,527","10,086","2,012","834,572"
1890,San Francisco,"2,012","834,572","9,093","5,747","7,145","2,013","845,063"
1891,San Francisco,"2,013","845,063","8,949","5,461","6,036","2,014","854,587"
1892,San Francisco,"2,014","854,587","9,104","5,634","6,348","2,015","864,405"
1893,San Francisco,"2,015","864,405","8,996","5,704","4,584","2,016","872,281"
1894,San Francisco,"2,016","872,281","9,011","5,766","4,817","2,017","880,343"
1895,San Francisco,"2,017","880,343","8,665","5,947","3,557","2,018","886,618"
1896,San Francisco,"2,018","886,618","8,669","5,839",-88,"2,019","889,360"
1897,San Francisco,"2,019","889,360","8,609","6,098",409,"2,020","892,280"
1898,San Francisco,"2,020","892,280","8,387","6,262","1,456","2,021","895,861"
1899,San Francisco,"2,021","895,861","8,125","6,434","2,495","2,022","900,047"
1900,San Francisco,"2,022","900,047","7,914","6,586","3,545","2,023","904,920"
1901,San Francisco,"2,023","904,920","7,732","6,668","4,590","2,024","910,574"
1902,San Francisco,"2,024","910,574","7,570","6,844","5,635","2,025","916,935"
1903,San Francisco,"2,025","916,935","7,307","7,061","5,376","2,026","922,557"
1904,San Francisco,"2,026","922,557","7,029","7,173","5,507","2,027","927,920"
1905,San Francisco,"2,027","927,920","6,912","7,303","5,657","2,028","933,186"
1906,San Francisco,"2,028","933,186","6,738","7,284","5,846","2,029","938,486"
1907,San Francisco,"2,029","938,486","6,651","7,440","6,118","2,030","943,815"
1908,San Francisco,"2,030","943,815","6,495","7,583","6,394","2,031","949,121"
1909,San Francisco,"2,031","949,121","6,399","7,803","6,664","2,032","954,381"
1910,San Francisco,"2,032","954,381","6,333","7,880","6,918","2,033","959,752"
1911,San Francisco,"2,033","959,752","6,438","7,903","7,204","2,034","965,491"
1912,San Francisco,"2,034","965,491","6,545","8,060","7,496","2,035","971,472"
1913,San Francisco,"2,035","971,472","6,652","8,110","7,751","2,036","977,765"
1914,San Francisco,"2,036","977,765","6,848","8,300","7,943","2,037","984,256"
1915,San Francisco,"2,037","984,256","7,125","8,395","8,180","2,038","991,166"
1916,San Francisco,"2,038","991,166","7,415","8,619","8,343","2,039","998,305"
1917,San Francisco,"2,039","998,305","7,766","8,808","8,499","2,040","1,005,762"
1918,San Francisco,"2,040","1,005,762","7,966","8,785","8,627","2,041","1,013,570"
1919,San Francisco,"2,041","1,013,570","8,179","9,137","8,704","2,042","1,021,316"
1920,San Francisco,"2,042","1,021,316","8,314","9,327","8,720","2,043","1,029,023"
1921,San Francisco,"2,043","1,029,023","8,501","9,470","8,686","2,044","1,036,740"
1922,San Francisco,"2,044","1,036,740","8,680","9,641","8,735","2,045","1,044,514"
1923,San Francisco,"2,045","1,044,514","8,722","9,697","8,682","2,046","1,052,221"
1924,San Francisco,"2,046","1,052,221","8,823","9,819","8,645","2,047","1,059,870"
1925,San Francisco,"2,047","1,059,870","9,146","9,950","8,533","2,048","1,067,599"
1926,San Francisco,"2,048","1,067,599","9,288","9,920","8,414","2,049","1,075,381"
1927,San Francisco,"2,049","1,075,381","9,395","10,078","8,305","2,050","1,083,003"
1928,San Francisco,"2,050","1,083,003","9,380","10,088","8,121","2,051","1,090,416"
1929,San Francisco,"2,051","1,090,416","9,389","10,216","7,974","2,052","1,097,563"
1930,San Francisco,"2,052","1,097,563","9,472","10,252","7,765","2,053","1,104,548"
1931,San Francisco,"2,053","1,104,548","9,635","10,301","7,589","2,054","1,111,471"
1932,San Francisco,"2,054","1,111,471","9,800","10,391","7,454","2,055","1,118,334"
1933,San Francisco,"2,055","1,118,334","9,710","10,407","7,313","2,056","1,124,950"
1934,San Francisco,"2,056","1,124,950","9,637","10,593","7,241","2,057","1,131,235"
1935,San Francisco,"2,057","1,131,235","9,552","10,667","7,184","2,058","1,137,304"
1936,San Francisco,"2,058","1,137,304","9,538","10,721","7,096","2,059","1,143,217"
1937,San Francisco,"2,059","1,143,217","9,514","10,819","7,059","2,060","1,148,971"

In [16]:
(
    pop_estimate_components_df[
        pop_estimate_components_df['County'].isin(bay_area_counties)
    ]
    .drop(columns=['County'])
    .groupby('Start Year')
    .sum()
    .applymap(lambda x: '{:,d}'.format(x) if isinstance(x, int) else x)
)

,Start Population,Births,Deaths,Net migrants,End Year,End Population
Start Year,,,,,,
2010,"7,177,970","87,958","45,332","43,072","18,099","7,263,668"
2011,"7,263,668","86,070","45,348","54,696","18,108","7,359,086"
2012,"7,359,086","87,975","46,773","47,654","18,117","7,447,942"
2013,"7,447,942","87,180","45,943","46,572","18,126","7,535,751"
2014,"7,535,751","88,154","47,814","45,425","18,135","7,621,516"
2015,"7,621,516","87,529","48,339","21,813","18,144","7,682,519"
2016,"7,682,519","85,482","49,670","12,605","18,153","7,730,936"
2017,"7,730,936","82,315","49,945","7,258","18,162","7,770,564"
2018,"7,770,564","81,163","49,208","-6,284","18,171","7,796,235"
2019,"7,796,235","80,199","50,790",-418,"18,180","7,825,226"
2020,"7,825,226","78,815","52,525","7,221","18,189","7,858,737"
2021,"7,858,737","77,704","54,110","14,850","18,198","7,897,181"
2022,"7,897,181","76,979","55,653","22,494","18,207","7,941,001"
2023,"7,941,001","76,539","57,298","30,126","18,216","7,990,368"
2024,"7,990,368","76,235","58,793","37,758","18,225","8,045,568"
2025,"8,045,568","76,428","60,174","37,324","18,234","8,099,146"
2026,"8,099,146","76,356","61,405","37,833","18,243","8,151,930"
2027,"8,151,930","76,663","62,921","38,363","18,252","8,204,035"
2028,"8,204,035","76,527","64,670","38,934","18,261","8,254,826"
2029,"8,254,826","76,708","66,336","39,629","18,270","8,304,827"
2030,"8,304,827","76,619","67,597","40,281","18,279","8,354,130"
2031,"8,354,130","77,088","69,034","40,944","18,288","8,403,128"
2032,"8,403,128","77,429","70,743","41,516","18,297","8,451,330"
2033,"8,451,330","78,204","72,192","42,054","18,306","8,499,396"
2034,"8,499,396","79,086","74,072","42,535","18,315","8,546,945"
2035,"8,546,945","79,865","75,755","42,895","18,324","8,593,950"
2036,"8,593,950","80,878","77,259","43,098","18,333","8,640,667"
2037,"8,640,667","81,797","79,424","43,226","18,342","8,686,266"
2038,"8,686,266","82,501","81,481","43,273","18,351","8,730,559"
2039,"8,730,559","83,370","83,128","43,264","18,360","8,774,065"
2040,"8,774,065","83,812","84,870","43,241","18,369","8,816,248"
2041,"8,816,248","84,006","86,349","43,101","18,378","8,857,006"
2042,"8,857,006","84,082","88,102","42,828","18,387","8,895,814"
2043,"8,895,814","83,973","89,762","42,471","18,396","8,932,496"
2044,"8,932,496","83,598","91,077","42,242","18,405","8,967,259"
2045,"8,967,259","82,894","91,943","41,958","18,414","9,000,168"
2046,"9,000,168","82,265","93,206","41,720","18,423","9,030,947"
2047,"9,030,947","81,910","94,188","41,457","18,432","9,060,126"
2048,"9,060,126","81,115","94,980","41,245","18,441","9,087,506"
2049,"9,087,506","80,354","96,088","41,138","18,450","9,112,910"
2050,"9,112,910","79,774","96,413","40,875","18,459","9,137,146"
2051,"9,137,146","79,456","96,911","40,677","18,468","9,160,368"
2052,"9,160,368","79,317","97,114","40,447","18,477","9,183,018"
2053,"9,183,018","79,112","97,275","40,270","18,486","9,205,125"
2054,"9,205,125","79,247","97,615","40,148","18,495","9,226,905"
2055,"9,226,905","78,928","98,006","40,005","18,504","9,247,832"
2056,"9,247,832","79,097","98,249","39,984","18,513","9,268,664"
2057,"9,268,664","79,359","98,220","40,027","18,522","9,289,830"
2058,"9,289,830","79,495","98,278","40,067","18,531","9,311,114"
2059,"9,311,114","79,702","98,123","40,188","18,540","9,332,881"

In [127]:
historical_components_df.loc[lambda x: x['County'] == 'San Francisco']

,County,Year,Population (July 1),Percent Change,Numeric Change,Births,Deaths,Natural Increase,Net Migration,Net Foreign Immigration,Net Domestic Migration
458,San Francisco,Apr-Jun 2010,810369.0,0.637578,5134.0,2117.0,1302.0,815.0,4319.0,1684.0,2635.0
459,San Francisco,2011,821235.0,1.340871,10866.0,8897.0,5727.0,3170.0,7696.0,7151.0,545.0
460,San Francisco,2012,834572.0,1.624017,13337.0,8778.0,5527.0,3251.0,10086.0,7040.0,3046.0
461,San Francisco,2013,845063.0,1.257052,10491.0,9093.0,5747.0,3346.0,7145.0,7068.0,77.0
462,San Francisco,2014,854587.0,1.127017,9524.0,8949.0,5461.0,3488.0,6036.0,6694.0,-658.0
463,San Francisco,2015,864405.0,1.148859,9818.0,9104.0,5634.0,3470.0,6348.0,6869.0,-521.0
464,San Francisco,2016,872281.0,0.911147,7876.0,8996.0,5704.0,3292.0,4584.0,7430.0,-2846.0
465,San Francisco,2017,880343.0,0.924243,8062.0,9011.0,5766.0,3245.0,4817.0,6629.0,-1812.0
466,San Francisco,2018,886618.0,0.712790,6275.0,8665.0,5947.0,2718.0,3557.0,5541.0,-1984.0
467,San Francisco,2019,889360.0,0.309265,2742.0,8669.0,5839.0,2830.0,-88.0,5200.0,-5288.0

In [22]:
(
    historical_components_df
    .loc[lambda x: x['County'].isin(bay_area_counties)]
    .drop(columns=['County', 'Percent Change'])
    .groupby('Year').sum()
    .applymap('{:,.0f}'.format)
    .reindex(['Apr-Jun 2010'] + list(range(2011, 2020)))
)

,Population (July 1),Numeric Change,Births,Deaths,Natural Increase,Net Migration,Net Foreign Immigration,Net Domestic Migration
Year,,,,,,,,
Apr-Jun 2010,"7,177,970","27,231","21,725","10,992","10,733","16,498","7,841","8,657"
2011,"7,263,668","85,698","87,958","45,332","42,626","43,072","34,036","9,036"
2012,"7,359,086","95,418","86,070","45,348","40,722","54,696","32,109","22,587"
2013,"7,447,942","88,856","87,975","46,773","41,202","47,654","32,075","15,579"
2014,"7,535,751","87,809","87,180","45,943","41,237","46,572","39,512","7,060"
2015,"7,621,516","85,765","88,154","47,814","40,340","45,425","48,259","-2,834"
2016,"7,682,519","61,003","87,529","48,339","39,190","21,813","50,595","-28,782"
2017,"7,730,936","48,417","85,482","49,670","35,812","12,605","48,205","-35,600"
2018,"7,770,564","39,628","82,315","49,945","32,370","7,258","45,204","-37,946"
2019,"7,796,235","25,671","81,163","49,208","31,955","-6,284","42,572","-48,856"